name: workflow-dispatch
on:
  workflow_dispatch:
    inputs: #inputs를 설정하면 수동으로 workflow를 실행할때 inputs를 임의로 수정 할 수 있음
      name:
        description: 'set name'
        required: true
        default: 'github-actions'
        type: string
      environment:
        description: 'set env'
        required: true
        default: 'dev'
        type: choice
        options:
        - dev
        - qa
        - prod

jobs:
  workflow-dispatch-job:
    runs-on: ubuntu-latest
    steps:
    - name: step1
      run: echo hello world
    - name: step2
      run: |
        echo hello world
        echo github action
    - name: echo inputs
      run: |
        echo ${{ inputs.name }}
        echo ${{ inputs.environment }}
