name: needs
on: push

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: echo "job1 done"
  job2:
    runs-on: ubuntu-latest
    needs: [job1] #job1에 대한 종속성이 있음 . job1이 완료 된 후 실행
    steps:
      - name: echo
        run: echo "job2 done"

  job3: #기본적으로 Job들은 병렬적으로 실행되기 때문에 Job1,job3은 병렬로 실행됨
    runs-on: ubuntu-latest
    steps: #일부러 실패시킴
      - name: echo
        run: |
          echo "job3 failed"
          exit 1 

  job4:
    runs-on: ubuntu-latest
    needs: [job3] #job4는 job3에 종속성이 있는데 job3이 실패하기 때문에 job4는 실행되지 않고 스킵됨
    steps:
      - name: echo
        run: echo "job4 done"